version: '3.8'

services:
  init:
    image: busybox
    command: echo "Initialization complete"
    networks:
      - bot_network

  app:
    build:
      context: .
      dockerfile: Dockerfile.good
    container_name: telegram_bot
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - bot_network

  db:
    image: postgres:13
    container_name: postgres_db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - bot_network

volumes:
  db_data:

networks:
  bot_network:
