FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libopenblas-dev \
    && rm -rf /var/lib/apt/lists/*

# COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt

RUN pip install --no-cache-dir \
    faiss-cpu \
    numpy \
    flask

COPY faiss_server.py .

CMD ["python", "faiss_server.py"]