version: '3.8'

services:
  init:
    image: busybox
    container_name: init_service
    command: sh -c "echo 'Initializing...' && sleep 5 && echo 'Initialization complete'"
    networks:
      - bot_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: telegram_rag_bot:latest
    container_name: telegram_bot
    depends_on:
      - init
      - faiss_db
    volumes:
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - FAISS_SERVICE_URL=http://faiss_db:5000
    command: ["python", "main.py"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://faiss_db:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - bot_network

  faiss_db:
    build:
      context: .
      dockerfile: Dockerfile.faiss
    container_name: faiss_db
    volumes:
      - faiss_data:/app/faiss_index
    ports:
      - "5000:5000"
    command: ["python", "faiss_server.py"]
    networks:
      - bot_network

volumes:
  faiss_data:

networks:
  bot_network:
    name: bot_network